apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: koding
  namespace: default
spec:
  ports:
  - name: ""
    nodePort: 0 
    port: 8090
    protocol: ""
    targetPort: 8090 
  selector:
    service: koding
  externalIPs:
  - "10.0.189.187"
  - "10.0.100.37"
  - "10.0.80.219"
  - "10.0.85.180"
status:
  loadBalancer: {}
