apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mongo
  namespace: default
spec:
  ports:
  - name: ""
    port: 27017 
    protocol: ""
    targetPort: 27017
  selector:
    service: mongo
status:
  loadBalancer: {}
