apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: postgres
  namespace: default
spec:
  ports:
  - name: ""
    port: 5432 
    protocol: ""
    targetPort: 5432
  selector:
    service: postgres
status:
  loadBalancer: {}
