apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq
  namespace: default
spec:
  ports:
  - name: rabbitmq-main
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: rabbitmq-2 
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: rabbitmq-3
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: rabbitmq-4
    port: 15671
    protocol: TCP
    targetPort: 15671
  - name: rabbitmq-5
    port: 25672
    protocol: TCP
    targetPort: 25672
  selector:
    service: rabbitmq
status:
  loadBalancer: {}
