apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: redis
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    service: redis
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: ""
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
