apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: redis
  namespace: default
spec:
  ports:
  - name: ""
    port: 6379
    protocol: ""
    targetPort: 6379
  selector:
    service: redis
status:
  loadBalancer: {}
